services:
  ipfs:
    image: ipfs/kubo:v0.40.1
    container_name: ipfs
    command: daemon --enable-gc --migrate=true
    ports:
      - "4001:4001"          # Swarm port (talks to the public IPFS network)
      - "127.0.0.1:8080:8080" # Gateway port (This is what your Python script hooks into)
      - "127.0.0.1:5001:5001" # API port (For Web UI access)
    volumes:
      - ./export:/export
      - ./ipfs_data:/data/ipfs
    restart: always

volumes:
  ipfs_storage: