import pandas as pd
import os

# Configuration
INPUT_FILE = "../data/output/error_nfts.csv"  # The file generated by decode_nft.py with errors
OUTPUT_REPORT = "../data/errors_analysis/error_analysis_report_latest.csv"


def analyze():
    # 1. Load the data
    try:
        df = pd.read_csv(INPUT_FILE)
    except FileNotFoundError:
        print(f"Error: {INPUT_FILE} not found.")
        return

    # 2. Count errors and calculate percentages
    error_counts = df['error'].value_counts()
    total = len(df)

    report_df = pd.DataFrame({
        'ERROR_TYPE': error_counts.index,
        'COUNT': error_counts.values,
        'PERCENTAGE': (error_counts.values / total * 100).round(2).astype(str) + '%'
    })

    # 3. Print to terminal
    print(f"Analyzing {INPUT_FILE}...\n")
    print(report_df.to_string(index=False))

    # 4. Save to CSV
    report_df.to_csv(OUTPUT_REPORT, index=False)
    print(f"\n✅ Full report saved to: {OUTPUT_REPORT}")


if __name__ == "__main__":
    analyze()
